name: CI
on:
  push:

jobs:
  build: 
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.build.outputs.version}}
    steps:
      - id: hello
        run: |
          echo "Hello GH-600"
          echo "Workflow completed">>$GITHUB_STEP_SUMMARY
          echo "version=1.2.3">>$GITHUB_OUTPUT

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: echo "Version received is ${{needs.hello.outputs.version}}"

        


